version: "3.7"
services:
    server:
        image: downmany:1.0
        container_name: downmany-server
        ports:
          - 8000:8000
        networks:
            - common-network

    client1:
        image: downmany:1.0
        container_name: downmany-client1
        volumes:
            - "./datasets/dataset1:/app/dataset"
        ports:
          - 8081:8080
        networks:
            - common-network
        depends_on:
            - server

    client2:
        image: downmany:1.0
        container_name: downmany-client2
        volumes:
            - "./datasets/dataset2:/app/dataset"
        ports:
          - 8082:8080
        networks:
            - common-network
        depends_on:
            - client1

    client3:
        image: downmany:1.0
        container_name: downmany-client3
        volumes:
            - "./datasets/dataset3:/app/dataset"
        ports:
          - 8083:8080
        networks:
            - common-network
        depends_on:
            - client2

networks:
    common-network:
        driver: bridge

volumes:
    db:
    pgadmindata:
